### ISSUE TITLE
Oversized word

### ISSUE THREAD

**Issue by jdrobbie** [Grimzentide/iRacing-Arduino-Pit-Board#13]
As shown in attached picture, when running a test session, the session laps input word of "Unlimited" is too big for the box. Not a fault or problem, just an observation. Maybe an abbreviation could be used instead.

![12048802_10153300909224209_570028417_n](https://cloud.githubusercontent.com/assets/12523386/10186781/333917f0-67b0-11e5-9180-cdf04d311635.jpg)

**Comment by Grimzentide** [comment]
Confirmed... Tired to use the infinity sign but it is not supported but the font pack I use.  Will implement an abbreviation in v1.0

**Comment by Grimzentide** [comment]
Fixed in v1.0
