### ISSUE TITLE
trying to get it to work on a 3.5 inch display.

### ISSUE THREAD

**Issue by mcapilot** [Grimzentide/iRacing-Arduino-Pit-Board#26]

**Comment by mcapilot** [comment]
I have tried the instructions and nothing is working.  I realized what they sent me was not a 2.8, but a 3.5.  I actually don't mind the larger size, but it's not working.  Any suggestions.

**Comment by Grimzentide** [comment]
I need more information on the device you received.

**Comment by mcapilot** [comment]
Upon further research it looks like the card I have works with controller
ILI9488 480x320 resolution.

**Comment by Grimzentide** [comment]
Check out how the arduino code was written for an ILI9341... This might give some insight on how to use the correct library for the ILI9488.

https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/blob/master/arduinopitboard_ILI9341.ino

**Comment by mcapilot** [comment]
Okay, I received the proper 2.8 inch tft card today.  I amn still not having any luck.  Any chance we could do a teamviewer session and you show me what I am doing wrong?  I would gladly send another donation.  Let me know.

Thanks, 

Mike

**Comment by Grimzentide** [comment]
Which TFT shield did you receive?

On Sat, Nov 28, 2015 at 8:22 AM, mcapilot <notifications@github.com> wrote:

> Okay, I received the proper 2.8 inch tft card today. I amn still not
> having any luck. Any chance we could do a teamviewer session and you show
> me what I am doing wrong? I would gladly send another donation. Let me know.
>
> Thanks,
>
> Mike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160205950>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
I received the Pixnor UNO R3 2.8 TFT Touch creen with SD Card Socket for
Arduino Board Module.  no other markings on it other than 2.6"/2.8" TFT LCD
Shield on the back.

**Comment by Grimzentide** [comment]
Can you walk me through what you have done?  Where did you get up to in the
install procedure?

https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/blob/master/Install%20Procedure.md

On Sat, Nov 28, 2015 at 10:33 AM, mcapilot <notifications@github.com> wrote:

> I received the Pixnor UNO R3 2.8 TFT Touch creen with SD Card Socket for
> Arduino Board Module. no other markings on it other than 2.6"/2.8" TFT LCD
> Shield on the back.
>
> On Fri, Nov 27, 2015 at 6:24 PM, Grimzentide <notifications@github.com>
> wrote:
>
> > Which TFT shield did you receive?
> >
> > On Sat, Nov 28, 2015 at 8:22 AM, mcapilot <notifications@github.com>
> > wrote:
> >
> > > Okay, I received the proper 2.8 inch tft card today. I amn still not
> > > having any luck. Any chance we could do a teamviewer session and you
> show
> > > me what I am doing wrong? I would gladly send another donation. Let me
> > know.
> > >
> > > Thanks,
> > >
> > > Mike
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160205950
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cheers
> > Brock Cremer
> > 0490 349 462
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160226630
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160227004>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
Hello,

Thanks for working with me.  I have only done one other arduino project,
the LED speedo, gear and shift lights with the TM1638.  That one I have
working.

So heree is what i have done.

I have Arduino IDE soft ware installed.
I have the Adafruit GFX graphics core library installed in \
Arduino\Sketchbook\libraries
It is on COM port 5
I open the Adadfruit TFT example sketch then I get this error:

Arduino: 1.6.5 (Windows 8.1), Board: "Arduino/Genuino Uno"

graphicstest.pde:5:54: fatal error: Adafruit_GFX.h: No such file or
directory
compilation terminated.
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

When I go to Tools > Serial Monitor it says Initializing SD card...Failed!

It does that with or with out an SD card present.

That is as far as I get.

Thanks,

Mike

**Comment by Grimzentide** [comment]
It seems the GFX library is in the wrong directory or something...

Verify the install path and check that you can see Adafruit_GFX.h in there.

Place the Adafruit_GFX library folder your <arduinosketchfolder>/Libraries/
> folder. You may need to create the Libraries subfolder if its your first
> library. Restart the IDE.


https://github.com/adafruit/Adafruit-GFX-Library


I am not sure why the sd card is causing an error....  It should matter in
the test sketch.


On Sun, Nov 29, 2015 at 2:26 AM, mcapilot <notifications@github.com> wrote:

> Hello,
>
> Thanks for working with me. I have only done one other arduino project,
> the LED speedo, gear and shift lights with the TM1638. That one I have
> working.
>
> So heree is what i have done.
>
> I have Arduino IDE soft ware installed.
> I have the Adafruit GFX graphics core library installed in \
> Arduino\Sketchbook\libraries
> It is on COM port 5
> I open the Adadfruit TFT example sketch then I get this error:
>
> Arduino: 1.6.5 (Windows 8.1), Board: "Arduino/Genuino Uno"
>
> graphicstest.pde:5:54: fatal error: Adafruit_GFX.h: No such file or
> directory
> compilation terminated.
> Error compiling.
>
> This report would have more information with
> "Show verbose output during compilation"
> enabled in File > Preferences.
>
> When I go to Tools > Serial Monitor it says Initializing SD card...Failed!
>
> It does that with or with out an SD card present.
>
> That is as far as I get.
>
> Thanks,
>
> Mike
>
>
> On Fri, Nov 27, 2015 at 6:45 PM, Grimzentide <notifications@github.com>
> wrote:
>
>
> > Can you walk me through what you have done? Where did you get up to in
> the
> > install procedure?
> >
> >
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/blob/master/Install%20Procedure.md
> >
> > On Sat, Nov 28, 2015 at 10:33 AM, mcapilot <notifications@github.com>
> > wrote:
> >
> > > I received the Pixnor UNO R3 2.8 TFT Touch creen with SD Card Socket
> for
> > > Arduino Board Module. no other markings on it other than 2.6"/2.8" TFT
> > LCD
> > > Shield on the back.
> > >
> > > On Fri, Nov 27, 2015 at 6:24 PM, Grimzentide <notifications@github.com
> >
> > > wrote:
> > >
> > > > Which TFT shield did you receive?
> > > >
> > > > On Sat, Nov 28, 2015 at 8:22 AM, mcapilot <notifications@github.com>
> > > > wrote:
> > > >
> > > > > Okay, I received the proper 2.8 inch tft card today. I amn still
> not
> > > > > having any luck. Any chance we could do a teamviewer session and
> you
> > > show
> > > > > me what I am doing wrong? I would gladly send another donation. Let
> > me
> > > > know.
> > > > >
> > > > > Thanks,
> > > > >
> > > > > Mike
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160205950
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Cheers
> > > > Brock Cremer
> > > > 0490 349 462
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160226630
> > > >
> > > > .
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160227004
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cheers
> > Brock Cremer
> > 0490 349 462
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160227420
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160310342>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
Yes.  I double and triple checked and the file is there.  I even downloaded
the library again in case it was corrupted.  No luck.

**Comment by Grimzentide** [comment]
Can you upload any of the example sketches from Arduino to the device?  Try the blink code first and see if that works....

**Comment by mcapilot** [comment]
No.  I get nothing.  I am about to give up.  I know it has to be something
simple, but I am pulling my hair out.  I appreciate your trying to help.

Thanks,

Mike

**Comment by Grimzentide** [comment]
Hmm,

Are you using a genuine arduino or a clone?

On Tue, Dec 1, 2015 at 11:07 AM, mcapilot <notifications@github.com> wrote:

> No. I get nothing. I am about to give up. I know it has to be something
> simple, but I am pulling my hair out. I appreciate your trying to help.
>
> Thanks,
>
> Mike
>
> On Mon, Nov 30, 2015 at 6:51 PM, Grimzentide <notifications@github.com>
> wrote:
>
> > Can you upload any of the example sketches from Arduino to the device?
> Try
> > the blink code first and see if that works....
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160801542
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160804411>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
a clone.  It is and Inland brand.

**Comment by Grimzentide** [comment]
Do you have a link to where you bought the device?  Some clones require a
different driver to get them functioning because the standard arduino one
does not work.

On Tue, Dec 1, 2015 at 11:13 AM, mcapilot <notifications@github.com> wrote:

> a clone. It is and Inland brand.
>
>
> On Mon, Nov 30, 2015 at 7:09 PM, Grimzentide <notifications@github.com>
> wrote:
>
> > Hmm,
> >
> > Are you using a genuine arduino or a clone?
> >
> > On Tue, Dec 1, 2015 at 11:07 AM, mcapilot <notifications@github.com>
> > wrote:
> >
> > > No. I get nothing. I am about to give up. I know it has to be something
> > > simple, but I am pulling my hair out. I appreciate your trying to help.
> > >
> > > Thanks,
> > >
> > > Mike
> > >
> > > On Mon, Nov 30, 2015 at 6:51 PM, Grimzentide <notifications@github.com
> >
> > > wrote:
> > >
> > > > Can you upload any of the example sketches from Arduino to the
> device?
> > > Try
> > > > the blink code first and see if that works....
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160801542
> > > >
> > > > .
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160804411
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cheers
> > Brock Cremer
> > 0490 349 462
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160804754
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160805317>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
http://www.microcenter.com/product/431997/Uno_R3_MainBoard  I have a
feeling I have missed a step or have something in wrong directory.  I have
been over everything , but no luck.  I am usually very computer literate.
This is stumping me.

**Comment by mcapilot** [comment]
If you or anybody you know using this setup, would like to take over my pc
via TeamViewer or something.  I would be happy to turn over the controls.

**Comment by Grimzentide** [comment]
It is starting to sound like a warranty issue for the board and not a code
or setup issue.

Maybe contact the place of purchase for assistance.

On Tue, Dec 1, 2015 at 11:29 AM, mcapilot <notifications@github.com> wrote:

> If you or anybody you know using this setup, would like to take over my pc
> via TeamViewer or something. I would be happy to turn over the controls.
>
>
> On Mon, Nov 30, 2015 at 6:51 PM, Grimzentide <notifications@github.com>
> wrote:
>
> > Can you upload any of the example sketches from Arduino to the device?
> Try
> > the blink code first and see if that works....
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160801542
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160808144>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by mcapilot** [comment]
I have tried two different boards.  I have another i am using for led shift
lights.  I have swapped boards and its doing the same thing.  Both work
with the TM1638 display.  But neither work with the 2.8 inch or 3.6 inch
TFT displays.

**Comment by Grimzentide** [comment]
I am now officially confused, so I might re-cap some questions again..

1. Can you upload any code to the arduino device when the TFT screen is not
attached?
2. Can you upload the same code to the other device you have?
3. Do the ports in windows change when you plug in both devices?

Brock

On Tue, Dec 1, 2015 at 11:56 AM, mcapilot <notifications@github.com> wrote:

> I have tried two different boards. I have another i am using for led shift
> lights. I have swapped boards and its doing the same thing. Both work
> with the TM1638 display. But neither work with the 2.8 inch or 3.6 inch
> TFT displays.
> On Nov 30, 2015 19:51, "Grimzentide" <notifications@github.com> wrote:
>
> > It is starting to sound like a warranty issue for the board and not a
> code
> > or setup issue.
> >
> > Maybe contact the place of purchase for assistance.
> >
> > On Tue, Dec 1, 2015 at 11:29 AM, mcapilot <notifications@github.com>
> > wrote:
> >
> > > If you or anybody you know using this setup, would like to take over my
> > pc
> > > via TeamViewer or something. I would be happy to turn over the
> controls.
> > >
> > >
> > > On Mon, Nov 30, 2015 at 6:51 PM, Grimzentide <notifications@github.com
> >
> > > wrote:
> > >
> > > > Can you upload any of the example sketches from Arduino to the
> device?
> > > Try
> > > > the blink code first and see if that works....
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160801542
> > > >
> > > > .
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160808144
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cheers
> > Brock Cremer
> > 0490 349 462
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160811539
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/issues/26#issuecomment-160812376>
> .
>



-- 
Cheers
Brock Cremer
0490 349 462

**Comment by redion1992** [comment]
I'm working on getting this to run with a 3.6" display I got, as I sit a long way back from the screen.

Here's the link, for reference: http://www.ebay.com.au/itm/262398292863?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT It has a hardware ID of 0x9486.

Firstly, I'm utilising a different LCD hardware library, from https://github.com/prenticedavid/MCUFRIEND_kbv . 

The changes are as follows: 
`#include <Adafruit_GFX.h>    // Core graphics library
//#include <Adafruit_TFTLCD.h> // Hardware-specific library
#include <MCUFRIEND_kbv.h>

//Adafruit_TFTLCD tft(LCD_CS, LCD_CD, LCD_WR, LCD_RD, LCD_RESET);
MCUFRIEND_kbv tft;`

All well and good, except the display is 480x320, rather than the designed 320x240. Is there an easy way to upsize the graphics to take up the full screen?

**Comment by Grimzentide** [comment]
Sadly no.  The text and lines are all done via co-ordinates which means you would manually have to update each section of code.  I used [moqups](https://moqups.com/brockcremer@gmail.com/ssilfetL/p:abe0f0011) to work out the co-ordinates of both the screens.  

The lines you would need to change would be...
fieldLimitLeft = x;
fieldLimitRight = x;
tft.setCursor(x, y);
tft.drawRect(2, 0, 317, 50, RED);              //Box Row 1
  
tft.drawFastVLine(101, 0, 50, RED);
tft.drawFastVLine(207, 0, 50, RED);
tft.drawRect(2, 52, 317, 50, RED);             //Box Row 2
tft.drawFastVLine(101, 52, 50, RED);
tft.drawFastVLine(207, 52, 50, RED);
tft.drawRect(2, 104, 317, 84, RED);            //Box Row 3
tft.drawRect(2, 190, 317, 50, RED);            //Box Row 4
tft.drawFastVLine(101, 190, 50, RED);
tft.drawFastVLine(207, 190, 50, RED);

**Comment by redion1992** [comment]
OK, I'm working on an updated version now using a #define statement. So all people will need to do is uncomment one line (plus the appropriate bits for their LCD board, if necessary) and it should switch everything.

**Comment by redion1992** [comment]
And got it working. Here's a link: https://github.com/redion1992/iRacing-Arduino-Pit-Board/blob/master/arduinopitboard.ino

**Comment by Grimzentide** [comment]
Any chance I can get a photo of how it looks on a bigger screen?

**Comment by redion1992** [comment]
Here's my take over on [moqups](https://moqups.com/redion1992@gmail.com/6ixioiBi).

And [here's](http://imgur.com/a/c46l5) a few images.

**Comment by Grimzentide** [comment]
It appears that I can increase the maximum number of characters in the information messages box.  Right now (from memory) it is set to 26.  Can you work out what the character limit would be on the new screen?

If you open up the arduino serial monitor, set it to 250000 baud and sent the following command, it should give you an indication of the character limits.

`-@1234567890123456789012345678901234567890!`

**Comment by redion1992** [comment]
I'd say a max of 38 characters. 39 is doable, but it bumps right up against the right edge of the box. 40 is where it starts to wrap.

**Comment by Grimzentide** [comment]
to be released in v2.62

**Comment by Miki-555** [comment]
some news on 3.5
