### ISSUE TITLE
How to install LCD TFT screen on raspberry

### ISSUE THREAD

**Issue by titan0007** [Grimzentide/iRacing-Arduino-Pit-Board#31]
Hi,

I bought a TFT SCREEN on a chinese web site. Unfortunaltely, there is no details on the HW board and no manual...

The link is : http://fr.aliexpress.com/item/2015-New-Raspberry-pi-LCD-display-Raspberry-pi-2-3-5-inch-SPI-TFT-touch-Display/32438329746.html

The pin used are :  raspi2B link to LCD board
	pin 2 & 4 → 5V
	GPIO 7 : SPI_CEL_N  link to L_CS
	GPIO 8 : SPI_CEO_N  link to T_CS
	GPIO 25: GPIO_GEN6  link to IRQ
	GPIO 11: CLK  link to CLK
	GPIO 9 : MISO  link to MISO
	GPIO 10: MOSI  link to MOSI

I tried to contact the seller without any response.
I tried to follow the install guide from some sites without success.

The screen is actually white (seems working).

How to configure LCD and TFT on Jessie image ?
How to define which HW is used (like ilixxx or adsxxx)?

Thanks for your help.

**Comment by Grimzentide** [comment]
This is a raspberry pi screen and not an arduino screen.  My code is not designed to work with this screen with the current graphics libraries.

**Comment by Grimzentide** [comment]
Marked as wont fix given it is not an arduino screen
