### ISSUE TITLE
Alph3 build 2 issue - shutting down...?

### ISSUE THREAD

**Issue by mapdaddy** [Grimzentide/iRacing-Arduino-Pit-Board#42]
Brock, I downloaded the Alpha 3 build 2 and installed it.  But I am still having an issue.

When I tested it I did 4 laps and then pitted.  All was fine, the program switched to the Pit Screen as it should and switched back to the main screen on leaving the pits.  But then for some reason the program seems to shut itself down.  When I enter the pits then after a further 4 laps nothing happens.  On checking the DOS screen has gone and the program seems to have shutdown.

**Comment by Grimzentide** [comment]
missing bracket on line 516
sendViaSerial('E' + str(fuelRequiredAtPitstopVarPitScreen**)** + '!')	    # FUEL REQUIRED AT STOP
