### ISSUE TITLE
Won't let me change my chip code to 0x9341 and change line for shield tft // bit 

### ISSUE THREAD

**Issue by wayno1** [Grimzentide/iRacing-Arduino-Pit-Board#46]
Had the pit board screen boarders up no numbers ready to go then couldn't get the info to it from iracing . Uninstalled everything and started again .got to the graphics test all good . Now try to load the tft stuff for pit board but I can't change two parts I need to ,to get the pit board boarders two show again ,one is the line for tft shield // instead of the breakout board .and then my chip I'd 0x9341  both are not letting me change now so I'm sort of stuck at this stage .how do I change the code in my files now .? It let me do it first time now it says I'm not able to change any of the files .  

![image](https://cloud.githubusercontent.com/assets/20653756/17173562/de8a02c4-543e-11e6-8def-fc76e73b6ae3.jpeg)
![image](https://cloud.githubusercontent.com/assets/20653756/17173564/df055708-543e-11e6-86e4-3471cec3d424.jpeg)

**Comment by Grimzentide** [comment]
resolved
