### ISSUE TITLE
Many white lines

### ISSUE THREAD

**Issue by jwolfie48** [Grimzentide/iRacing-Arduino-Pit-Board#47]
I am trying to get the sketch to work with my uno and lcd tft display. I currently am getting white lines all the way across the screen. I have verified the display and it works fine with the graphics test. I have the ILI9341 LCD Driver and am running the sketch with that. I was wondering what i need to do to fix this issue.

Thanks

**Comment by Grimzentide** [comment]
Are you using this code on the arduino?

https://github.com/Grimzentide/iRacing-Arduino-Pit-Board/blob/master/arduinopitboard_ILI9341/arduinopitboard_ILI9341.ino

**Comment by jwolfie48** [comment]
Yes i was id did figure out and it was working great. I have to re download it as i just installed a new hard drive ant the program is not working at the moment

**Comment by Grimzentide** [comment]
OK, just released a new version because of some issues after the latest week 13 release by iRacing.

**Comment by Grimzentide** [comment]
If this is still an issue please message me on the iRacing and I can find a time to log on and help you.
