### ISSUE TITLE
Avg fuel burn outside of car

### ISSUE THREAD

**Issue by jdrobbie** [Grimzentide/iRacing-Arduino-Pit-Board#57]
Feature request - on the screen that gets presented when you exit the car after a session that shows the general last session info, is there a chance of adding the avg fuel lap burn as well?

Once you exit the car from the pits, you appear to lose that information so if you don't look (or don't take off your VR before like I forget) before you exit the car, you cant recall that information.

**Comment by Grimzentide** [comment]
Added to dev list.  Should be pretty easy to do.

**Comment by Grimzentide** [comment]
Feature added to v4.6

**Comment by Grimzentide** [comment]
Version 4.6 released
