### ISSUE TITLE
BR: Fuel calc is way off

### ISSUE THREAD

**Issue by rasssta** [Grimzentide/iRacing-Arduino-Pit-Board#58]
Hi,

I recently did a race in VRS GT Sprint with Mercedes AMG GT3 at Laguna Seca. When it was time for the pit stop IRAPB said I should add 18 litres while Crew chief said 14 litres. I chose to add 17L instead and ended up crossing the finish line with >5L to spare. A bit too much, as 2L would have been more than enough. I launched IRAPB with no options other than the com-port.

Also, for some reason IRAPB thought I added 16.23 L during the pit stop (when I chose to add 17L).

What's up? :-)

I haven't done any more races yet but I will add more info when I have.

**Comment by Grimzentide** [comment]
Hey Rasssta,

The default value for timed races is 2 laps worth of fuel.  You can override this value by using the -fcl argument (aka fuel contingency laps).

eg.  -fcl 0.5 would be half a lap of fuel extra, which is what I run when I race.

Work out how much risk you are willing to take with this number remembering drafting and quicker drivers might sometimes cause an extra lap of racing.

The difference between the 17L you added and it displaying 16.23L is what you burned exiting pit lane.  The fuel added calculation is displayed as you exit.

**Comment by rasssta** [comment]
Thanks for the explanation. Please update the docs at https://github.com/Grimzentide/iRacing-Arduino-Pit-Board as it implies 0.5 laps of fuel as default.

"Note: The calculations for required fuel automatically includes an extra half of a lap to ensure you can cross the finish line. The half lap fuel addition is calculated using half of the current 5 lap average fuel burn rate and is automatically included in the required fuel figure."
